# Generated by Django 5.0.4 on 2024-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='word_to_display',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chaturbate_url',
            field=models.URLField(default='https://chaturbate.com/in/?tour=dT8X&campaign=rvN8K&track=default&room=herbal_sommelier', max_length=256, verbose_name='Ссылка на Chaturbate'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fansly_block_header',
            field=models.TextField(default='Subscribe to my Fansly!', verbose_name='Заголовок блока Fansly'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fansly_block_image',
            field=models.ImageField(default=0, upload_to='post_images', verbose_name='Фото для блока Fansly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fansly_block_text',
            field=models.TextField(default='<h3>🔥 A lot of hot videos and photos</h3><h3>📷 New photo every day</h3><h3>📹 New long video every few days</h3><h3>💬 Private messages and chat with me</h3><h3>🎫 Free entry to ticket shows on Chaturbate</h3><h3>🎁 Special gift</h3><br>', verbose_name='Текст блока Fansly'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fansly_url',
            field=models.URLField(default='https://www.fans.ly/r/herbalsomml/', max_length=256, verbose_name='Ссылка на Fansly'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/herbalsomml/', max_length=256, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='links_button_nav_text',
            field=models.CharField(default='Links', max_length=15, verbose_name='Текст кнопки блока ссылок в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='load_more_button_text',
            field=models.CharField(default='Load more', max_length=30, verbose_name='Текст кнопки загрузки контента'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='qa_block_header',
            field=models.TextField(default='Questions & Answers', verbose_name='Заголовок блока вопрос ответ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='qa_button_nav_text',
            field=models.CharField(default='Q&A', max_length=15, verbose_name='Текст кнопки блока вопросов в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='running_line_text',
            field=models.CharField(default='FIRST MONTH -20% • A LOT OF HOT CONTENT • $0,32 PER A DAY • SUBSCRIBE AND WATCH!', max_length=1024, verbose_name='Текст бегущей строки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(default='https://www.herbalsomml.online/', max_length=256, verbose_name='Ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_media_block_header',
            field=models.TextField(default='Follow my social pages!', verbose_name='Заголовок блока социальных сетей'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_media_block_image',
            field=models.ImageField(default=1, upload_to='post_images', verbose_name='Фото для блока социальных сетей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_media_block_text',
            field=models.TextField(default='<h3>Enjoy free videos, photos and new announcements every day.</h3><h3>It\'s really hot!</h3><br><div class="btn-instagram-borders mb-3"><button class="btn-instagram"><i class="fa fa-instagram"></i> Instagram</button></div><div class="btn-twitter-borders mb-3"><button class="btn-twitter"><i class="fa fa-twitter"></i> Twitter</button></div>', verbose_name='Текст блока социальных сетей'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripchat_url',
            field=models.URLField(default='https://stripchat.com/AyeBassota/follow-me', max_length=256, verbose_name='Ссылка на Stripchat'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subscribe_button_text_one',
            field=models.CharField(default='Subscribe', max_length=15, verbose_name='Первая часть текста кнопки подписки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subscribe_button_text_two',
            field=models.CharField(default='and watch', max_length=15, verbose_name='Вторая часть текста кнопки подписки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(default='https://t.me/+SNEN4dqJJR9jY2Yy/', max_length=256, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(default='https://www.twitter.com/herbalsomml/', max_length=256, verbose_name='Ссылка на Twitter'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_block_header',
            field=models.TextField(default='Newest videos!', verbose_name='Заголовок блока видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_button_nav_text',
            field=models.CharField(default='Videos', max_length=30, verbose_name='Текст кнопки блока видео в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='watch_button_text',
            field=models.CharField(default='Watch it!', max_length=30, verbose_name='Текст кнопки просмотра'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webcam_block_header',
            field=models.TextField(default='Join my live shows!', verbose_name='Заголовок блока Webcam'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webcam_block_image',
            field=models.ImageField(default=1, upload_to='post_images', verbose_name='Фото для блока Webcam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webcam_block_text',
            field=models.TextField(default='<h3>We can chat together, do naughty things, or just have a great time together 😊</h3><br><div class="btn-chaturbate-borders mb-2"><button class="btn-chaturbate"><i class="fa fa-camera"></i> Chaturbate</button></div><br>', verbose_name='Текст блока Webcam'),
        ),
    ]
