# Generated by Django 5.0.4 on 2024-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_sitesettings_word_to_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fansly_button_text',
            field=models.CharField(default='Subscribe and get 1 day free', max_length=40, verbose_name='Текст кнопки в блоке Fansly'),
        ),
    ]
