# Generated by Django 5.0.4 on 2024-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_sitesettings_fansly_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='model_name',
            field=models.URLField(default='Herbal Sommelier', max_length=256, verbose_name='Имя модели'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_media_block_text',
            field=models.TextField(default="<h3>Enjoy free videos, photos and new announcements every day.</h3><h3>It's really hot!</h3><br>", verbose_name='Текст блока социальных сетей'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='webcam_block_text',
            field=models.TextField(default='<h3>We can chat together, do naughty things, or just have a great time together 😊</h3><br>', verbose_name='Текст блока Webcam'),
        ),
    ]
