# Generated by Django 5.0.4 on 2024-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_sitesettings_site_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='fansly_block_image',
            field=models.ImageField(upload_to='video_images', verbose_name='Фото для блока Fansly'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_media_block_image',
            field=models.ImageField(upload_to='video_images', verbose_name='Фото для блока социальных сетей'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='webcam_block_image',
            field=models.ImageField(upload_to='video_images', verbose_name='Фото для блока Webcam'),
        ),
    ]
