# Generated by Django 5.0.4 on 2024-04-25 08:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'default_related_name': 'videos', 'ordering': ('-pub_date',), 'verbose_name': 'видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 10, 6, 40, 59180), verbose_name='Добавлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 10, 6, 54, 413818), help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', verbose_name='Дата и время публикации'),
            preserve_default=False,
        ),
    ]
