# Generated by Django 5.0.4 on 2024-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'default_related_name': 'videos', 'ordering': ('pub_date',), 'verbose_name': 'видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='to_slider',
            field=models.BooleanField(default=False),
        ),
    ]
