# Generated by Django 5.0.4 on 2024-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_alter_video_options_alter_video_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'default_related_name': 'questions', 'ordering': ('position',), 'verbose_name': 'вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
