# Generated by Django 5.0.4 on 2024-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_question_options_remove_question_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='video_images', verbose_name='Фото'),
        ),
    ]
