# Generated by Django 4.2.13 on 2024-05-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_city_studio_delete_question_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='max_payouts',
            field=models.IntegerField(default=90, verbose_name='Максимальный процент выплаты модели'),
        ),
        migrations.AddField(
            model_name='studio',
            name='min_payouts',
            field=models.IntegerField(default=50, verbose_name='Минимальный процент выплаты модели'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Города работы'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='english',
            field=models.BooleanField(default=False, verbose_name='Требуется ли знание английского'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='experience',
            field=models.CharField(choices=[('noexperience', 'Без опыта'), ('less6month', 'Меньше 6 месяцев'), ('from6monthto1year', 'От 6 месяцев'), ('morethenyear', 'От года')], max_length=20, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='format',
            field=models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], max_length=20, verbose_name='Формат раоты'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='gender',
            field=models.CharField(choices=[('female', 'Девушки'), ('male', 'Парни'), ('couples', 'Пары'), ('trans', 'Транс')], max_length=20, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='payouts',
            field=models.CharField(choices=[('everyday', 'Ежедневно'), ('1perweek', '1 раз в неделю'), ('1permonth', '1 раз в месяц'), ('2permonth', '2 раза в месяц')], max_length=30, verbose_name='Выплаты'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='shifts',
            field=models.CharField(choices=[('morning', 'Утренние'), ('day', 'Дневные'), ('evening', 'Вечерние'), ('night', 'Ночные')], max_length=30, verbose_name='Смены'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, verbose_name='Телеграм аккаунт'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='website',
            field=models.URLField(blank=True, max_length=258, verbose_name='Ссылка на сайт'),
        ),
    ]
