# Generated by Django 4.2.13 on 2024-05-25 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_studio_cities_studio_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormatChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenderChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutsChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftsChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='studio',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='format',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='gender',
        ),
        migrations.AlterField(
            model_name='studio',
            name='max_age',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(85)], verbose_name='Максильмальный возраст модели'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='max_payouts',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный процент выплаты модели'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='min_age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(85)], verbose_name='Минимальный возраст модели'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='min_payouts',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальный процент выплаты модели'),
        ),
        migrations.RemoveField(
            model_name='studio',
            name='payouts',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='shifts',
        ),
        migrations.AddField(
            model_name='studio',
            name='experience',
            field=models.ManyToManyField(to='main.experiencechoices', verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='studio',
            name='format',
            field=models.ManyToManyField(to='main.formatchoices', verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='studio',
            name='gender',
            field=models.ManyToManyField(to='main.genderchoices', verbose_name='Гендер'),
        ),
        migrations.AddField(
            model_name='studio',
            name='payouts',
            field=models.ManyToManyField(to='main.payoutschoices', verbose_name='Выплаты'),
        ),
        migrations.AddField(
            model_name='studio',
            name='shifts',
            field=models.ManyToManyField(to='main.shiftschoices', verbose_name='Опыт работы'),
        ),
    ]
