# Generated by Django 4.2.13 on 2024-05-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_max_payouts_studio_max_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='is_it_premium',
            field=models.BooleanField(default=False, verbose_name='Это премиум размещение?'),
        ),
        migrations.AddField(
            model_name='studio',
            name='is_it_vip',
            field=models.BooleanField(default=False, verbose_name='Это VIP размещение?'),
        ),
        migrations.AddField(
            model_name='studio',
            name='when_it_ends',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
