# Generated by Django 4.2.13 on 2024-05-25 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studio_is_it_premium_studio_is_it_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatchoices',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studio',
            name='shifts',
            field=models.ManyToManyField(to='main.shiftschoices', verbose_name='Смены'),
        ),
    ]
