# Generated by Django 4.2.13 on 2024-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_experiencechoices_icon_genderchoices_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='contact_button_icon',
            field=models.CharField(default='fa-solid fa-message', max_length=128, verbose_name='Иконка кнопки связаться для премиума'),
        ),
        migrations.AddField(
            model_name='studio',
            name='contact_button_text',
            field=models.CharField(default='Связаться', max_length=256, verbose_name='Текст кнопки связи для премиума'),
        ),
    ]
