# Generated by Django 4.2.13 on 2024-05-25 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studio_contact_button_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
