# Generated by Django 4.2.13 on 2024-05-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_studio_is_it_vip_studio_is_it_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='short_description',
        ),
    ]
