# Generated by Django 4.2.13 on 2024-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_studio_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.URLField(max_length=258, verbose_name='Ссылка')),
                ('small_image', models.ImageField(upload_to='', verbose_name='Для маленьких устройств')),
                ('medium_image', models.ImageField(upload_to='', verbose_name='Для средних устройств')),
                ('large_image', models.ImageField(upload_to='', verbose_name='Для больших устройств')),
                ('when_it_ends', models.DateTimeField(blank=True, default=None, null=True, verbose_name='До какого момента будет отображаться на сайте')),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='experiencechoices',
            options={'verbose_name': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='formatchoices',
            options={'verbose_name': 'Тип студии'},
        ),
        migrations.AlterModelOptions(
            name='genderchoices',
            options={'verbose_name': 'Гендер', 'verbose_name_plural': 'гендеры'},
        ),
        migrations.AlterModelOptions(
            name='payoutschoices',
            options={'verbose_name': 'Выплата', 'verbose_name_plural': 'выплаты'},
        ),
        migrations.AlterModelOptions(
            name='shiftschoices',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'смены'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': 'Студия', 'verbose_name_plural': 'студии'},
        ),
    ]
