# Generated by Django 4.2.13 on 2024-05-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_miniad_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='experiencechoices',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='formatchoices',
            options={'verbose_name': 'Тип студии', 'verbose_name_plural': 'Типы студий'},
        ),
        migrations.AlterField(
            model_name='studio',
            name='contact_button_icon',
            field=models.CharField(blank=True, default='fa-solid fa-message', max_length=128, verbose_name='Иконка кнопки связаться для премиума'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='contact_button_link',
            field=models.CharField(blank=True, default='#', max_length=128, verbose_name='Ссылка для кнопки связаться премиума'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='contact_button_text',
            field=models.CharField(blank=True, default='Связаться', max_length=256, verbose_name='Текст кнопки связи для премиума'),
        ),
    ]
